// autogenerated by sequelize model:create --name TodoItem --attributes content:string,complete:boolean and then added classMethods
module.exports = (sequelize, DataTypes) => {
  const TodoItem = sequelize.define('TodoItem', {
    content: {
      type: DataTypes.STRING,
      allowNull: false,//added
    },
    complete: {
      type: DataTypes.BOOLEAN,
      defaultValue: false, //added
    },
  }, {
    classMethods: {
      associate: (models) => {
        TodoItem.belongsTo(models.Todo, {
          foreignKey: 'todoId',
          onDelete: 'CASCADE',
        });
      },
    },
  });
  return TodoItem;
};
